apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - image: mysql:8.0
      name: mysql
      envFrom:
        - secretRef:
            name: istory-db-secret
        - configMapRef:
            name: istory-db-config
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:  #PV 마운트
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes: # volume 선언
    - name: mysql-persistent-storage
      persistentVolumeClaim: # PVC 생성
        claimName: mysql-pv-claim